name: Save Docker Image as TAR (Multi-Arch)

on:
  workflow_dispatch:
    inputs:
      image_domain:
        description: "镜像仓库"
        required: true
        default: "docker.io"
      image_name:
        description: "镜像名称"
        required: true
        default: "ubuntu"
      image_tag:
        description: "镜像tag"
        required: true
        default: "latest"
      arch:
        description: "系统架构(如arm64, amd64)"
        required: true
        default: "arm64"

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Skopeo
        run: sudo apt-get install -y skopeo

      - name: Pull & Save Specific Arch Image
        id: save_step
        run: |
          FULL_IMAGE="${{ github.event.inputs.image_domain }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}"
          ARCH="${{ github.event.inputs.arch }}"
          CLEAN_ARCH=$(echo "$ARCH" | sed 's|linux/||')
          ATRIFACT_NAME="${{ github.event.inputs.image_name }}_${{ github.event.inputs.image_tag }}_${CLEAN_ARCH}"
          FILENAME="${{ github.event.inputs.image_name }}_${{ github.event.inputs.image_tag }}_${CLEAN_ARCH}.tar"
          echo "正在抓取架构 [$CLEAN_ARCH] 的镜像: $FULL_IMAGE"
          echo "输出文件名: $FILENAME"
          skopeo copy --override-os linux --override-arch "$CLEAN_ARCH" docker://$FULL_IMAGE docker-archive:${FILENAME}:$FULL_IMAGE
          echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
          echo "artifact_name=${ATRIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Upload TAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.save_step.outputs.artifact_name }}
          path: ${{ steps.save_step.outputs.filename }}
